**Imports**

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pprint import pprint as pp
import csv
from pathlib import Path

**Pandas Configuration Options**

In [ ]:
pd.set_option('max_columns', 200)
pd.set_option('max_rows', 300)
pd.set_option('display.expand_frame_repr', True)

**Data Files Location**

* Most data files for the exercises can be found on the [course site](https://www.datacamp.com/courses/merging-dataframes-with-pandas)
    * [Baby Names](https://assets.datacamp.com/production/repositories/516/datasets/43c9b6bf4c283ab024b2d7d61fbf15a0baa1e44d/Baby%20names.zip)
    * [Summer Olympic Medals](https://assets.datacamp.com/production/repositories/516/datasets/2d14df8d3c6a1773358fa000f203282c2e1107d6/Summer%20Olympic%20medals.zip)
    * [Automobile Fuel Efficiency](https://assets.datacamp.com/production/repositories/516/datasets/2f3d8b2156d5669fb7e12137f1c2e979c3c9ce0b/automobiles.csv)
    * [Exchange Rates](https://assets.datacamp.com/production/repositories/516/datasets/e91482db6a7bae394653278e4e908e63ed9ac833/exchange.csv)
    * [GDP](https://assets.datacamp.com/production/repositories/516/datasets/a0858a700501f88721ca9e4bdfca99b9e10b937f/GDP.zip)
    * [Oil Prices](https://assets.datacamp.com/production/repositories/516/datasets/707566cf46c4dd6290b9029f5e07a92baf3fe3f7/oil_price.csv)
    * [Pittsburgh Weather](https://assets.datacamp.com/production/repositories/516/datasets/58c1ead59818b2451324e9e84239db7bda6b11d3/pittsburgh2013.csv)
    * [Sales](https://assets.datacamp.com/production/repositories/516/datasets/2b89c1b00016e1ebcfd7f08a127d2c79589ce5c0/Sales.zip)
    * [S&P 500](https://assets.datacamp.com/production/repositories/516/datasets/7a9b570a02ef589891d9576a86876a616ca5f3c8/sp500.csv)
* Other data files may be found in my [DataCamp repository](https://github.com/trenton3983/DataCamp/tree/master/data)

**Data File Objects**

In [ ]:
data = Path.cwd() / 'data'
auto_fuel_file = data / 'auto_fuel_efficiency.csv'
baby_1881_file = data / 'baby_names1881.csv'
baby_1981_file = data / 'baby_names1981.csv'
exch_rates_file = data / 'exchange_rates.csv'
gdp_china_file = data / 'gdp_china.csv'
gdp_usa_file = data / 'gdp_usa.csv'
oil_price_file = data / 'oil_price.csv'
pitts_file = data / 'pittsburgh_weather_2013.csv'
sales_feb_hardware_file = data / 'sales-feb-Hardware.csv'
sales_feb_service_file = data / 'sales-feb-Service.csv'
sales_feb_software_file = data / 'sales-feb-Software.csv'
sales_jan_2015_file = data / 'sales-jan-2015.csv'
sales_feb_2015_file = data / 'sales-feb-2015.csv'
sales_mar_2015_file = data / 'sales-mar-2015.csv'
sp500_file = data / 'sp500.csv'
so_bronze_file = data / 'summer_olympics_Bronze.csv'
so_bronze5_file = data / 'summer_olympics_bronze_top5.csv'
so_gold_file = data / 'summer_olympics_Gold.csv'
so_gold5_file = data / 'summer_olympics_gold_top5.csv'
so_silver_file = data / 'summer_olympics_Silver.csv'
so_silver5_file = data / 'summer_olympics_silver_top5.csv'
so_all_medalists_file = data / 'summer_olympics_medalists 1896 to 2008 - ALL MEDALISTS.tsv'
so_editions_file = data / 'summer_olympics_medalists 1896 to 2008 - EDITIONS.tsv'
so_ioc_codes_file = data / 'summer_olympics_medalists 1896 to 2008 - IOC COUNTRY CODES.csv'

# Merging DataFrames with pandas

***Course Description***

As a Data Scientist, you'll often find that the data you need is not in a single file. It may be spread across a number of text files, spreadsheets, or databases. You want to be able to import the data of interest as a collection of DataFrames and figure out how to combine them to answer your central questions. This course is all about the act of combining, or merging, DataFrames, an essential part of any working Data Scientist's toolbox. You'll hone your pandas skills by learning how to organize, reshape, and aggregate multiple data sets to answer your specific questions.

## Preparing Data

In this chapter, you'll learn about different techniques you can use to import multiple files into DataFrames. Having imported your data into individual DataFrames, you'll then learn how to share information between DataFrames using their Indexes. Understanding how Indexes work is essential information that you'll need for merging DataFrames later in the course.

### Reading multiple data files

#### Tools for pandas data import

* pd.read_csv() for CSV files
    * dataframe = pd.read_csv(filepath)
    * dozens of optional input parameters
* Other data import tools:
    * pd.read_excel()
    * pd.read_html()
    * pd.read_json()

#### Loading separate files

```python
import pandas as pd
dataframe0 = pd.read_csv('sales-jan-2015.csv')
dataframe1 = pd.read_csv('sales-feb-2015.csv')
```

#### Using a loop

```python
filenames = ['sales-jan-2015.csv', 'sales-feb-2015.csv']
dataframes = []
for f in filenames:
    dataframes.append(pd.read_csv(f))
```

#### Using a comprehension

```python
filenames = ['sales-jan-2015.csv', 'sales-feb-2015.csv']
dataframes = [pd.read_csv(f) for f in filenames]
```

#### Using glob

```python
from glob import glob
filenames = glob('sales*.csv')
dataframes = [pd.read_csv(f) for f in filenames]
```

### Exercises

#### Reading DataFrames from multiple files

#### Reading DataFrames from multiple files in a loop

#### Combining DataFrames from multiple data files

### Reindexing DataFrames

#### "Indexes" vs. "Indices"

* indices: many index labels within Index data structures
* indexes: many pandas Index data structures

![](https://raw.githubusercontent.com/trenton3983/DataCamp/master/Images/merging_dataframes_in_python/indices_indexes.JPG "Indices & Indexes")

#### Importing weather data

```python
import pandas as pd
w_mean = pd.read_csv('quarterly_mean_temp.csv', index_col='Month')
w_max = pd.read_csv('quarterly_max_temp.csv', index_col='Month')
```

#### Examining the data

```python
print(w_mean)
        Mean TemperatureF
Month
Apr     61.956044
Jan     32.133333
Jul     68.934783
Oct     43.434783

print(w_max)
        Max TemperatureF
Month
Jan     68
Apr     89
Jul     91
Oct     84
```

#### The DataFrame indexes

```python
print(w_mean.index)
Index(['Apr', 'Jan', 'Jul', 'Oct'], dtype='object', name='Month')

print(w_max.index)
Index(['Jan', 'Apr', 'Jul', 'Oct'], dtype='object', name='Month')

print(type(w_mean.index))
<class 'pandas.indexes.base.Index'>
```

#### Using .reindex()

```python
ordered = ['Jan', 'Apr', 'Jul', 'Oct']
w_mean2 = w_mean.reindex(ordered)
print(w_mean2)

        Mean TemperatureF
Month
Jan     32.133333
Apr     61.956044
Jul     68.934783
Oct     43.434783
```

#### Using .sort_index()

```python
w_mean2.sort_index()
        Mean TemperatureF
Month
Apr     61.956044
Jan     32.133333
Jul     68.934783
Oct     43.434783
```

#### Reindex from a DataFrame Index

```python
w_mean.reindex(w_max.index)
        Mean TemperatureF
Month
Jan     32.133333
Apr     61.956044
Jul     68.934783
Oct     43.434783
```

#### Reindexing with missing labels

```python
w_mean3 = w_mean.reindex(['Jan', 'Apr', 'Dec'])
print(w_mean3)
        Mean TemperatureF
Month
Jan     32.133333
Apr     61.956044
Dec     NaN
```

#### Reindex from a DataFrame Index

```python
w_max.reindex(w_mean3.index)
        Max TemperatureF
Month
Jan     68.0
Apr     89.0
Dec     NaN

w_max.reindex(w_mean3.index).dropna()
        Max TemperatureF
Month
Jan     68.0
Apr     89.0
```

#### Order matters

```python
w_max.reindex(w_mean.index)
        Max TemperatureF
Month
Apr     89
Jan     68
Jul     91
Oct     84

w_mean.reindex(w_max.index)
        Mean TemperatureF
Month
Jan     32.133333
Apr     61.956044
Jul     68.934783
Oct     43.434783
```

### Exercises

#### Sorting DataFrame with the Index & columns

#### Reindexing DataFrame from a list

#### Reindexing DataFrame using another DataFrame Index

### Arithmetic with Series & DataFrames

#### Loading weather data

```python
import pandas as pd
weather = pd.read_csv('pittsburgh2013.csv', index_col='Date', parse_dates=True)
weather.loc['2013-7-1':'2013-7-7', 'PrecipitationIn']

Date
2013-07-01 0.18
2013-07-02 0.14
2013-07-03 0.00
2013-07-04 0.25
2013-07-05 0.02
2013-07-06 0.06
2013-07-07 0.10
Name: PrecipitationIn, dtype: float64
```

#### Scalar multiplication

```python
weather.loc['2013-07-01':'2013-07-07', 'PrecipitationIn'] * 2.54

Date
2013-07-01 0.4572
2013-07-02 0.3556
2013-07-03 0.0000
2013-07-04 0.6350
2013-07-05 0.0508
2013-07-06 0.1524
2013-07-07 0.2540
Name: PrecipitationIn, dtype: float64
```

#### Absolute temperature range

```python
week1_range = weather.loc['2013-07-01':'2013-07-07', ['Min TemperatureF', 'Max TemperatureF']]
print(week1_range)
Min TemperatureF Max TemperatureF
Date
2013-07-01 66 79
2013-07-02 66 84
2013-07-03 71 86
2013-07-04 70 86
2013-07-05 69 86
2013-07-06 70 89
2013-07-07 70 77
```

#### Average temperature

```python
week1_mean = weather.loc['2013-07-01':'2013-07-07', 'Mean TemperatureF']
print(week1_mean)
Date
2013-07-01 72
2013-07-02 74
2013-07-03 78
2013-07-04 77
2013-07-05 76
2013-07-06 78
2013-07-07 72
Name: Mean TemperatureF, dtype: int64
```

#### Relative temperature range

```python
week1_range / week1_mean
RuntimeWarning: Cannot compare type 'Timestamp' with type 'str', sort order is
undefined for incomparable objects
return this.join(other, how=how, return_indexers=return_indexers)

2013-07-01 00:00:00 2013-07-02 00:00:00 2013-07-03 00:00:00 \
Date
2013-07-01 NaN NaN NaN
2013-07-02 NaN NaN NaN
2013-07-03 NaN NaN NaN
2013-07-04 NaN NaN NaN
2013-07-05 NaN NaN NaN
2013-07-06 NaN NaN NaN
2013-07-07 NaN NaN NaN
2013-07-04 00:00:00 2013-07-05 00:00:00 2013-07-06 00:00:00 \
Date
2013-07-01 NaN NaN NaN
... ...
```

#### Relative temperature range

```python
week1_range.divide(week1_mean, axis='rows')

Min TemperatureF Max TemperatureF
Date
2013-07-01 0.916667 1.097222
2013-07-02 0.891892 1.135135
2013-07-03 0.910256 1.102564
2013-07-04 0.909091 1.116883
2013-07-05 0.907895 1.131579
2013-07-06 0.897436 1.141026
2013-07-07 0.972222 1.069444
```

#### Percentage changes

```python
week1_mean.pct_change() * 100

Date
2013-07-01 NaN
2013-07-02 2.777778
2013-07-03 5.405405
2013-07-04 -1.282051
2013-07-05 -1.298701
2013-07-06 2.631579
2013-07-07 -7.692308
Name: Mean TemperatureF, dtype: float64
```

#### Bronze Olympic medals

```python
bronze = pd.read_csv('bronze_top5.csv', index_col=0)
print(bronze)
Total
Country
United States 1052.0
Soviet Union 584.0
United Kingdom 505.0
France 475.0
Germany 454.0
```

#### Silver Olympic medals

```python
silver = pd.read_csv('silver_top5.csv', index_col=0)
print(silver)
Total
Country
United States 1195.0
Soviet Union 627.0
United Kingdom 591.0
France 461.0
Italy 394.0
```

#### Gold Olympic medals

```python
gold = pd.read_csv('gold_top5.csv', index_col=0)
print(gold)
Total
Country
United States 2088.0
Soviet Union 838.0
United Kingdom 498.0
Italy 460.0
Germany 407.0
```

#### Adding bronze, silver

```python
bronze + silver

Country
France 936.0
Germany NaN
Italy NaN
Soviet Union 1211.0
United Kingdom 1096.0
United States 2247.0
Name: Total, dtype: float64
```

#### Adding bronze, silver

```python
bronze + silver

Country
France 936.0
Germany NaN
Italy NaN
Soviet Union 1211.0
United Kingdom 1096.0
United States 2247.0
Name: Total, dtype: float64
In [22]: print(bronze['United States'])
1052.0
In [23]: print(silver['United States'])
1195.0
```

#### Using the .add() method

```python
bronze.add(silver)

Country
France 936.0
Germany NaN
Italy NaN
Soviet Union 1211.0
United Kingdom 1096.0
United States 2247.0
Name: Total, dtype: float64
```

#### Using a fill_value

```python
bronze.add(silver, fill_value=0)

Country
France 936.0
Germany 454.0
Italy 394.0
Soviet Union 1211.0
United Kingdom 1096.0
United States 2247.0
Name: Total, dtype: float64
```

#### Adding bronze, silver, gold

```python
bronze + silver + gold

Country
France NaN
Germany NaN
Italy NaN
Soviet Union 2049.0
United Kingdom 1594.0
United States 4335.0
Name: Total, dtype: float64
```

#### Chaining .add()

```python
bronze.add(silver, fill_value=0).add(gold, fill_value=0)

Country
France 936.0
Germany 861.0
Italy 854.0
Soviet Union 2049.0
United Kingdom 1594.0
United States 4335.0
Name: Total, dtype: float64
```

### Exercises

#### Adding unaligned DataFrames

#### Broadcasting in Arithmetic formulas

#### Computing percentage growth of GDP

#### Converting currency of stocks

## Concatenating Data

Having learned how to import multiple DataFrames and share information using Indexes, in this chapter you'll learn how to perform database-style operations to combine DataFrames. In particular, you'll learn about appending and concatenating DataFrames while working with a variety of real-world datasets.

### Appending & concatenating Series

#### append()

* .append(): Series & DataFrame method
* Invocation:
* s1.append(s2)
* Stacks rows of s2 below s1
* Method for Series & DataFrames

#### concat()

* concat(): pandas module function
* Invocation:
* pd.concat([s1, s2, s3])
* Can stack row-wise or column-wise

#### concat() & .append()

* Equivalence of concat() & .append():
* result1 = pd.concat([s1, s2, s3])
* result2 = s1.append(s2).append(s3)
* result1 == result2 elementwise

#### Series of US states

```python
import pandas as pd
northeast = pd.Series(['CT', 'ME', 'MA', 'NH', 'RI', 'VT', 'NJ', 'NY', 'PA'])
south = pd.Series(['DE', 'FL', 'GA', 'MD', 'NC', 'SC', 'VA', 'DC', 'WV', 'AL', 'KY', 'MS', 'TN', 'AR', 'LA', 'OK', 'TX'])
midwest = pd.Series(['IL', 'IN', 'MN', 'MO', 'NE', 'ND', 'SD', 'IA', 'KS', 'MI', 'OH', 'WI'])
west = pd.Series(['AZ', 'CO', 'ID', 'MT',
```

#### Using .append()

```python
east = northeast.append(south)
print(east)
0 CT       7 DC
1 ME       8 WV
2 MA       9 AL
3 NH       10 KY
4 RI       11 MS
5 VT       12 TN
6 NJ       13 AR
7 NY       14 LA
8 PA       15 OK
0 DE       16 TX
1 FL       dtype: object
2 GA
3 MD
4 NC
5 SC
6 VA
```

#### The appended Index

```python
print(east.index)
Int64Index([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], dtype='int64')

print(east.loc[3])
3 NH
3 MD
dtype: object
```

#### Using .reset_index()

```python
new_east = northeast.append(south).reset_index(drop=True)
print(new_east.head(11))
0 CT
1 ME
2 MA
3 NH
4 RI
5 VT
6 NJ
7 NY
8 PA
9 DE
10 FL
dtype: object

print(new_east.index)
RangeIndex(start=0, stop=26, step=1)
```

#### Using concat()

```python
east = pd.concat([northeast, south])
print(east.head(11))
0 CT
1 ME
2 MA
3 NH
4 RI
5 VT
6 NJ
7 NY
8 PA
0 DE
1 FL
dtype: object
print(east.index)
Int64Index([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], dtype='int64')
```

#### Using ignore_index

```python
new_east = pd.concat([northeast, south], ignore_index=True)
print(new_east.head(11))
0 CT
1 ME
2 MA
3 NH
4 RI
5 VT
6 NJ
7 NY
8 PA
9 DE
10 FL
dtype: object
print(new_east.index)
RangeIndex(start=0, stop=26, step=1)
```

### Exercises

#### Appending Series with nonunique Indices

#### Appending pandas Series

#### Concatenating pandas Series along row axis

### Appending & concatenating DataFrames

#### Loading population data

```python
In [1]: import pandas as pd
In [2]: pop1 = pd.read_csv('population_01.csv', index_col=0)
In [3]: pop2 = pd.read_csv('population_02.csv', index_col=0)
In [4]: print(type(pop1), pop1.shape)
<class 'pandas.core.frame.DataFrame'> (4, 1)
In [5]: print(type(pop2), pop2.shape)
<class 'pandas.core.frame.DataFrame'> (4, 1)
```

#### Examining population data

```python
print(pop1)
2010 Census Population
Zip Code ZCTA
66407 479
72732 4716
50579 2405
46241 30670
print(pop2)

2010 Census Population
Zip Code ZCTA
12776 2180
76092 26669
98360 12221
49464 27481
```

#### Appending population DataFrames

```python
pop1.append(pop2)

2010 Census Population
Zip Code ZCTA
66407 479
72732 4716
50579 2405
46241 30670
12776 2180
76092 26669
98360 12221
49464 27481

print(pop1.index.name, pop1.columns)
Zip Code ZCTA Index(['2010 Census Population'], dtype='object')

print(pop2.index.name, pop2.columns)
Zip Code ZCTA Index(['2010 Census Population'], dtype='object')
```

#### Population & unemployment data

```python
population = pd.read_csv('population_00.csv', index_col=0)
unemployment = pd.read_csv('unemployment_00.csv', index_col=0)
print(population)
2010 Census Population
Zip Code ZCTA
57538 322
59916 130
37660 40038
2860 45199

print(unemployment)
unemployment participants
Zip
2860 0.11 34447
46167 0.02 4800
1097 0.33 42
80808 0.07 4310
```

#### Appending population & unemployment

```python
population.append(unemployment)
2010 Census Population participants unemployment
57538 322.0 NaN NaN
59916 130.0 NaN NaN
37660 40038.0 NaN NaN
2860 45199.0 NaN NaN
2860 NaN 34447.0 0.11
46167 NaN 4800.0 0.02
1097 NaN 42.0 0.33
80808 NaN 4310.0 0.07
```

#### Repeated index labels

```python
population.append(unemployment)

2010 Census Population participants unemployment
57538 322.0 NaN NaN
59916 130.0 NaN NaN
37660 40038.0 NaN NaN
2860 45199.0 NaN NaN
2860 NaN 34447.0 0.11
46167 NaN 4800.0 0.02
1097 NaN 42.0 0.33
80808 NaN 4310.0 0.07
```

#### Concatenating rows

```python
pd.concat([population, unemployment], axis=0)

2010 Census Population participants unemployment
57538 322.0 NaN NaN
59916 130.0 NaN NaN
37660 40038.0 NaN NaN
2860 45199.0 NaN NaN
2860 NaN 34447.0 0.11
46167 NaN 4800.0 0.02
1097 NaN 42.0 0.33
80808 NaN 4310.0 0.07
```

#### Concatenating columns

```python
pd.concat([population, unemployment], axis=1)

2010 Census Population unemployment participants
1097 NaN 0.33 42.0
2860 45199.0 0.11 34447.0
37660 40038.0 NaN NaN
46167 NaN 0.02 4800.0
57538 322.0 NaN NaN
59916 130.0 NaN NaN
80808 NaN 0.07 4310.0
```

### Exercises

#### Appending DataFrames with ignore_index

#### Concatenating pandas DataFrames along column axis

#### Reading multiple files to build a DataFrame

### Concatenation, keys & MultiIndexes

#### Loading rainfall data

```python
import pandas as pd
file1 = 'q1_rainfall_2013.csv'
rain2013 = pd.read_csv(file1, index_col='Month', parse_dates=True)
file2 = 'q1_rainfall_2014.csv'
rain2014 = pd.read_csv(file2, index_col='Month', parse_dates=True)
```

#### Examining rainfall data

```python
print(rain2013)
Precipitation
Month
Jan 0.096129
Feb 0.067143
Mar 0.061613

print(rain2014)
Precipitation
Month
Jan 0.050323
Feb 0.082143
Mar 0.070968
```

#### Concatenating rows

```python
pd.concat([rain2013, rain2014], axis=0)

Precipitation
Jan 0.096129
Feb 0.067143
Mar 0.061613
Jan 0.050323
Feb 0.082143
Mar 0.070968
```

#### Using multi-index on rows

```python
rain1314 = pd.concat([rain2013, rain2014], keys=[2013, 2014], axis=0)
print(rain1314)
Precipitation
2013 Jan 0.096129
Feb 0.067143
Mar 0.061613
2014 Jan 0.050323
Feb 0.082143
Mar 0.070968
```

#### Accessing a multi-index

```python
print(rain1314.loc[2014])
Precipitation
Jan 0.050323
Feb 0.082143
Mar 0.070968
```

#### Concatenating columns

```python
rain1314 = pd.concat([rain2013, rain2014], axis='columns')
print(rain1314)
Precipitation Precipitation
Jan 0.096129 0.050323
Feb 0.067143 0.082143
Mar 0.061613 0.070968
```

#### Using a multi-index on columns

```python
rain1314 = pd.concat([rain2013, rain2014], keys=[2013, 2014], axis='columns')
print(rain1314)
2013 2014
Precipitation Precipitation
Jan 0.096129 0.050323
Feb 0.067143 0.082143
Mar 0.061613 0.070968

print(rain1314[2013])
Precipitation
Jan 0.096129
Feb 0.067143
Mar 0.061613
```

#### pd.concat() with dict

```python
rain_dict = {2013: rain2013, 2014: rain2014}
rain1314 = pd.concat(rain_dict, axis='columns')
print(rain1314)
2013 2014
Precipitation Precipitation
Jan 0.096129 0.050323
Feb 0.067143 0.082143
Mar 0.061613 0.070968
```

### Exercises

#### Concatenating vertically to get MultiIndexed rows

#### Slicing MultiIndexed DataFrames

#### Concatenating horizontally to get MultiIndexed columns

#### Concatenating DataFrames from a dict

### Outer & inner joins

#### Using with arrays

In [ ]:
A = np.arange(8).reshape(2, 4) + 0.1
A

In [ ]:
B = np.arange(6).reshape(2,3) + 0.2
B

In [ ]:
C = np.arange(12).reshape(3,4) + 0.3
C

#### Stacking arrays horizontally

In [ ]:
np.hstack([B, A])

In [ ]:
np.concatenate([B, A], axis=1)

#### Stacking arrays vertically

In [ ]:
np.vstack([A, C])

In [ ]:
np.concatenate([A, C], axis=0)

#### Incompatible array dimensions

In [ ]:
np.concatenate([A, B], axis=0) # incompatible columns

In [ ]:
np.concatenate([A, C], axis=1) # incompatible rows

#### Population & unemployment data

```python
population = pd.read_csv('population_00.csv', index_col=0)

unemployment = pd.read_csv('unemployment_00.csv', index_col=0)
print(population)
2010 Census Population
Zip Code ZCTA
57538 322
59916 130
37660 40038
2860 45199

print(unemployment)
unemployment participants
Zip
2860 0.11 34447
46167 0.02 4800
1097 0.33 42
80808 0.07 4310
```

#### Converting to arrays

```python
population_array = np.array(population)
print(population_array) # Index info is lost
[[ 322]
[ 130]
[40038]
[45199]]

unemployment_array = np.array(unemployment)
print(population_array)
[[ 1.10000000e-01 3.44470000e+04]
[ 2.00000000e-02 4.80000000e+03]
[ 3.30000000e-01 4.20000000e+01]
[ 7.00000000e-02 4.31000000e+03]]
```

#### Manipulating data as arrays

```python
print(np.concatenate([population_array, unemployment_array], axis=1))
[[ 3.22000000e+02 1.10000000e-01 3.44470000e+04]
[ 1.30000000e+02 2.00000000e-02 4.80000000e+03]
[ 4.00380000e+04 3.30000000e-01 4.20000000e+01]
[ 4.51990000e+04 7.00000000e-02 4.31000000e+03]]
```

#### Joins

* Joining tables: Combining rows of multiple tables
* Outer join
    * Union of index sets (all labels, no repetition)
    * Missing fields filled with NaN
* Inner join
    * Intersection of index sets (only common labels)

#### Concatenation & inner join

```python
pd.concat([population, unemployment], axis=1, join='inner')

2010 Census Population unemployment participants
2860 45199 0.11 34447
```

#### Concatenation & outer join

```python
pd.concat([population, unemployment], axis=1, join='outer')

2010 Census Population unemployment participants
1097 NaN 0.33 42.0
2860 45199.0 0.11 34447.0
37660 40038.0 NaN NaN
46167 NaN 0.02 4800.0
57538 322.0 NaN NaN
59916 130.0 NaN NaN
80808 NaN 0.07 4310.0
```

#### Inner join on other axis

```python
pd.concat([population, unemployment], join='inner', axis=0)

Empty DataFrame
Columns: []
Index: [2860, 46167, 1097, 80808, 57538, 59916, 37660, 2860]
```

### Exercises

#### Concatenating DataFrames with inner join

#### Resampling & concatenating DataFrames with inner join

## Merging Data

Here, you'll learn all about merging pandas DataFrames. You'll explore different techniques for merging, and learn about left joins, right joins, inner joins, and outer joins, as well as when to use which. You'll also learn about ordered merging, which is useful when you want to merge DataFrames whose columns have natural orderings, like date-time columns.

### Merging DataFrames

### Exercises

#### Merging company DataFrames

#### Merging on a specific column

#### Merging on columns with non-matching labels

#### Merging on multiple columns

### Joining DataFrames

### Exercises

#### Joining by Index

#### Choosing a joining strategy

#### Left & right merging on multiple columns

#### Merging DataFrames with outer join

### Ordered merges

### Exercises

#### Using merge_ordered()

#### Using merge_asof()

## Case Study - Summer Olympics

To cement your new skills, you'll apply them by working on an in-depth study involving Olympic medal data. The analysis involves integrating your multi-DataFrame skills from this course and also skills you've gained in previous pandas courses. This is a rich dataset that will allow you to fully leverage your pandas data manipulation skills. Enjoy!

### Medals in the Summer Olympics

### Case Study Explorations

#### Loading Olympic edition DataFrame

#### Loading IOC codes DataFrames

#### Building medals DataFrame

### Quantifying Performance

### Case Study Explorations

#### Counting medals by country/edition in a pivot table

#### Computing fraction of medals per Olympic edition

#### Computing percentage change in fraction of medals won

### Reshaping and plotting

### Case Study Explorations

#### Building hosts DataFrame

#### Reshaping for analysis

#### Merging to compute influence

#### Plotting influence of host country

### Final Thoughts